### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by acarasimon96** [acarasimon96/nitter-ft#1]
This issue serves as the master todo list of the project.

### New features

- [x] Cookie-based home timeline and following users (zedeus/nitter#363)
- [ ] zedeus/nitter#159
- [x] zedeus/nitter#353
- [x] zedeus/nitter#437

### Enhancements, refactors

- [x] zedeus/nitter#432
- [x] zedeus/nitter#448
- [x] zedeus/nitter#324
- [x] zedeus/nitter#142
- [x] Remove deprecated packages (zedeus/nitter#369)
- [x] zedeus/nitter#258
- [ ] zedeus/nitter#406
- [ ] Update translations (zedeus/nitter#419)

Please see <https://github.com/zedeus/nitter/pulls> for a full list of open pull requests in the original Nitter project.

## Important bug fixes

- [ ] zedeus/nitter#428
  - Closed due to inactivity and the fact that the bug rarely occurs and is difficult to debug
- [x] Pin Nim version per https://github.com/zedeus/nitter/issues/452#issuecomment-940883665

## Endpoints to implement

- [ ] zedeus/nitter#234
- [x] zedeus/nitter#303

## Documentation

- [ ] Issue/PR templates
- [ ] CONTRIBUTING.md
- [ ] HACKING.md (how to get started on developing Nitter/Nitter FT)
- [ ] Add note in readme saying that the latest version of Nim is recommended

## Other new features, ideas

- [ ] Log Twitter API requests and responses for debugging
- [ ] Replace Twitter embeds (like Invidious)
- [ ] Nitter API
- [ ] Tweet/timeline archiving (zedeus/nitter#298)
- [x] Libreddit redirect support — merge with Teddit redirect support if possible like with Piped/Invidious
- [ ] Trending page/section (zedeus/nitter#61)
- [ ] Lists (probably cookie-based)
- [ ] Locale preferences and date/time format consistency
- [ ] Use external service (preferably one that is privacy-preserving) to crowdsource translations
- [ ] Hide Open on Twitter link in Settings and About pages
- [ ] More to come…
